name: Run clang-format check
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-23.11
    - run: nix develop --command python3 .github/scripts/run-clang-format.py -r cspot/src cspot/include